# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6b1f356a881562da30c67994a456fbb29f8bb8f4d7dad324bb5641499724938933463eb9950257ebc47003f0b546a423b5e4a83417d03889063dccb81b50869

test:
  secret_key_base: 02b7a81723b7c705d94937a797c0a7e1d689e09096b563a7f7b1bfbaa5dde01efe9dd9025210ac07963fe8e90f1f16b42a965780efcf2faf887c5e4e4b105cb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
